twig:
    file_name_pattern: '*.twig'
    form_themes: ['bootstrap_5_layout.html.twig']
    globals:
        tabService: '@App\Service\TabService'

when@test:
    twig:
        strict_variables: true
